version: '2'

services:
  cs-sgx:
    image: enclaive/cs-sgx
    build: .
    ports:
      - "443:443"
    devices:
      - "/dev/sgx/enclave:/dev/sgx/enclave"
      - "/dev/sgx/enclave:/dev/sgx_enclave"
      - "/dev/sgx_provision:/dev/sgx_provision"
